version: "3.4"
services:
  rabbit:
    image: zbytes/rabbitmq-3-management
    build:
      context: deployment
      dockerfile: rabbitmq.dockerfile
    ports:
      - 61613:61613
      - 15672:15672